import { Link, Route, Routes } from 'react-router-dom'
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { Alert, AppShell, EmptyState, Skeleton, StatusBadge, type Status } from './ui'
import { t } from './i18n'
import { productApi, type Product } from './mock-api'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
const Page=({title,children}:{title:string;children?:ReactNode})=><AppShell><div className="page-stack"><h1>{title}</h1>{children}</div></AppShell>
const dateTypeLabel=(type:Product['dateType'])=>type==='use_by'?'Годен до':'Лучше употребить до'
const ProductList=()=> {
  const [items,setItems]=useState<Product[]|null>(null)
  const [query,setQuery]=useState('')
  const [status,setStatus]=useState<Status|'all'>('all')
  useEffect(()=>{productApi.list().then(setItems)},[])
  const shown=useMemo(()=>items?.filter(p=>(status==='all'||p.status===status)&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.expiryDate.localeCompare(b.expiryDate))??[],[items,query,status])
  const urgent=useMemo(()=>items?.filter(p=>!['used','discarded'].includes(p.status)).sort((a,b)=>a.expiryDate.localeCompare(b.expiryDate)).slice(0,3)??[],[items])
  const complete=(id:string,next:'used'|'discarded')=>productApi.complete(id,next).then(()=>productApi.list()).then(setItems)
  return <AppShell><div className="inventory-layout"><div className="inventory-main page-stack"><header className="page-header"><div><p className="eyebrow">Панорама запаса</p><h1>{t.products}</h1><p className="page-subtitle">{items?.filter(p=>!['used','discarded'].includes(p.status)).length??'—'} {t.inventoryCount}</p></div><Link className="button-link" to="/products/new"><span aria-hidden="true">+</span>{t.add}</Link></header><section className="filters" aria-label="Фильтры"><label>{t.search}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></label><label>{t.status}<select value={status} onChange={e=>setStatus(e.target.value as Status|'all')}><option value="all">{t.allStatuses}</option><option value="active">Активен</option><option value="attention">Требует внимания</option><option value="expired">Срок истёк</option></select></label></section>{items===null?<section className="product-list" aria-busy="true"><Skeleton/><Skeleton/><Skeleton/></section>:shown.length===0?<EmptyState action={<Link className="button-link" to="/products/new">{t.add}</Link>}>{t.empty}</EmptyState>:<ul className="product-list" aria-label="Продукты">{shown.map(p=><li className={`product-card product-card--${p.status}`} key={p.id}><div className="product-card__identity"><p className="product-card__location">{p.location}</p><h2>{p.name}</h2><p className="product-card__group">{p.group}</p></div><div className="product-card__date"><span>{dateTypeLabel(p.dateType)}</span><time dateTime={p.expiryDate}>{p.expiryDate}</time></div><StatusBadge status={p.status}/>{!['used','discarded'].includes(p.status)&&<div className="product-card__actions"><button onClick={()=>complete(p.id,'used')}>{t.used}</button><button className="button-secondary" onClick={()=>complete(p.id,'discarded')}>{t.discarded}</button></div>}</li>)}</ul>}</div><aside className="urgency-rail" aria-labelledby="urgency-title"><div className="urgency-rail__heading"><p className="eyebrow">Ближайшее действие</p><h2 id="urgency-title">{t.urgency}</h2></div>{items===null?<Skeleton/>:<ul>{urgent.map((product,index)=><li key={product.id}><span className="urgency-rank">0{index+1}</span><div><strong>{product.name}</strong><p>{product.location} · <time dateTime={product.expiryDate}>{product.expiryDate}</time></p></div><StatusBadge status={product.status}/></li>)}</ul>}<div className="urgency-rail__note"><StatusBadge status="research_required"/><Alert>{t.ruleText}</Alert></div></aside></div></AppShell>}
const schema=z.object({name:z.string().trim().min(1,'Введите название'),dateType:z.enum(['use_by','best_before']),expiryDate:z.string().min(1,'Укажите дату'),location:z.string(),group:z.string()});type FormData=z.infer<typeof schema>
const Form=({title}:{title:string})=>{const [saved,setSaved]=useState(false);const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{name:'',dateType:'use_by',expiryDate:'',location:'',group:''}});const submit=async(data:FormData)=>{await productApi.create(data);setSaved(true)};return <Page title={title}><form className="form-card" onSubmit={handleSubmit(submit)} noValidate><div className="form-grid"><label>Название<input {...register('name')} aria-invalid={!!errors.name}/>{errors.name&&<span role="alert">{errors.name.message}</span>}</label><label>Тип даты<select {...register('dateType')}><option value="use_by">Годен до</option><option value="best_before">Лучше употребить до</option></select></label><label>Дата<input type="date" {...register('expiryDate')} aria-invalid={!!errors.expiryDate}/>{errors.expiryDate&&<span role="alert">{errors.expiryDate.message}</span>}</label><label>Место хранения<input {...register('location')}/></label><label>Группа<input {...register('group')}/></label></div><Alert tone="info">«Годен до» — дата безопасности. «Лучше употребить до» — дата качества.</Alert>{saved&&<Alert>Продукт добавлен</Alert>}<div className="form-actions"><button type="submit" disabled={isSubmitting}>{isSubmitting?'Сохраняем…':t.save}</button><Link to="/products/new/photo">{t.photo}</Link></div></form></Page>}
export function App(){return <Routes><Route path="/login" element={<Page title={t.login}><form className="card stack"><label>E-mail<input type="email"/></label><label>Пароль<input type="password"/></label><button>{t.login}</button><Link to="/register">{t.register}</Link></form></Page>}/><Route path="/register" element={<Page title={t.register}><Alert tone="warning">{t.profileBlocked}</Alert></Page>}/><Route path="/products" element={<ProductList/>}/><Route path="/products/new" element={<Form title={t.add}/>}/><Route path="/products/new/photo" element={<Page title={t.photo}><Skeleton/><Link to="/products/new">{t.manual}</Link></Page>}/><Route path="/product-drafts/:id" element={<Form title={t.draft}/>}/><Route path="/products/:id" element={<Page title="Продукт"><StatusBadge status="attention"/></Page>}/><Route path="/recipes" element={<Page title={t.recipes}><EmptyState action={<Link to="/products">{t.products}</Link>}>{t.noRecipes}</EmptyState></Page>}/><Route path="/settings" element={<Page title={t.settings}><Alert>{t.settingsBlocked}</Alert></Page>}/><Route path="*" element={<Page title={t.notFound}><Link to="/products">{t.back}</Link></Page>}/></Routes>}
