import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { useMemo, useState, type ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { api, ApiError, apiMode } from './api'
import { Alert, AppShell, EmptyState, Skeleton, StatusBadge, type Status } from './ui'
import { t } from './i18n'
import type { Product, ProductInput } from './mock-api'

const productKeys = { list: ['products'] as const, detail: (id: string) => ['products', id] as const }
const message = (error: unknown) => error instanceof ApiError && error.status === 401 ? 'Сессия завершена. Войдите снова.' : 'Не удалось выполнить действие. Проверьте соединение и повторите.'
const Page = ({ title, children }: { title: string; children?: ReactNode }) => <div className="page-stack"><h1>{title}</h1>{children}</div>
const PublicPage = ({ title, children }: { title: string; children?: ReactNode }) => <main id="main-content" className="public-page"><Page title={title}>{children}</Page></main>
const dateTypeLabel = (type: Product['dateType']) => type === 'use_by' ? 'Годен до' : 'Лучше употребить до'

function ProtectedLayout() {
  const location = useLocation()
  const session = useQuery({ queryKey: ['session'], queryFn: api.auth.session, retry: false, staleTime: 60_000 })
  if (session.isPending) return <PublicPage title={t.loading}><Skeleton /></PublicPage>
  if (session.isError) return <Navigate to="/login" replace state={{ from: location.pathname }} />
  return <AppShell><div className="private-content"><div className="account-actions"><LogoutButton /></div><Outlet /></div></AppShell>
}

function LogoutButton() {
  const navigate = useNavigate(); const queryClient = useQueryClient()
  const logout = useMutation({ mutationFn: api.auth.logout, onSuccess: () => { queryClient.removeQueries({ queryKey: ['session'] }); navigate('/login') } })
  return <button className="button-secondary" type="button" disabled={logout.isPending} onClick={() => logout.mutate()}>{logout.isPending ? 'Выходим…' : 'Выйти'}</button>
}

function RequestError({ retry }: { retry: () => void }) { return <Alert tone="danger">Не удалось загрузить данные. <button className="inline-retry" type="button" onClick={retry}>Повторить</button></Alert> }

function ProductList() {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<Status | 'all'>('all'); const queryClient = useQueryClient()
  const products = useQuery({ queryKey: productKeys.list, queryFn: api.products.list, retry: false })
  const complete = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'used' | 'discarded' }) => api.products.complete(id, action), onSuccess: () => queryClient.invalidateQueries({ queryKey: productKeys.list }) })
  const shown = useMemo(() => (products.data ?? []).filter((item) => (status === 'all' || item.status === status) && item.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.expiryDate.localeCompare(b.expiryDate)), [products.data, query, status])
  const urgent = useMemo(() => (products.data ?? []).filter((item) => !['used', 'discarded'].includes(item.status)).sort((a, b) => a.expiryDate.localeCompare(b.expiryDate)).slice(0, 3), [products.data])
  return <div className="inventory-layout"><div className="inventory-main page-stack"><header className="page-header"><div><p className="eyebrow">Панорама запаса</p><h1>{t.products}</h1><p className="page-subtitle">{products.data?.filter((item) => !['used', 'discarded'].includes(item.status)).length ?? '—'} {t.inventoryCount}</p></div><Link className="button-link" to="/products/new"><span aria-hidden="true">+</span>{t.add}</Link></header><section className="filters" aria-label="Фильтры"><label>{t.search}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} /></label><label>{t.status}<select value={status} onChange={(event) => setStatus(event.target.value as Status | 'all')}><option value="all">{t.allStatuses}</option><option value="active">Активен</option><option value="attention">Требует внимания</option><option value="expired">Срок истёк</option></select></label></section>{products.isPending ? <section className="product-list" aria-busy="true"><Skeleton /><Skeleton /><Skeleton /></section> : products.isError ? <RequestError retry={() => products.refetch()} /> : shown.length === 0 ? <EmptyState action={<Link className="button-link" to="/products/new">{t.add}</Link>}>{t.empty}</EmptyState> : <ul className="product-list" aria-label="Продукты">{shown.map((item) => <li className={`product-card product-card--${item.status}`} key={item.id}><div className="product-card__identity"><p className="product-card__location">{item.location || 'Не указано'}</p><h2><Link to={`/products/${item.id}`}>{item.name}</Link></h2><p className="product-card__group">{item.group || 'Без группы'}</p></div><div className="product-card__date"><span>{dateTypeLabel(item.dateType)}</span><time dateTime={item.expiryDate}>{item.expiryDate}</time></div><StatusBadge status={item.status} />{!['used', 'discarded'].includes(item.status) && <div className="product-card__actions"><button disabled={complete.isPending} onClick={() => complete.mutate({ id: item.id, action: 'used' })}>{complete.isPending ? 'Обновляем…' : t.used}</button><button className="button-secondary" disabled={complete.isPending} onClick={() => complete.mutate({ id: item.id, action: 'discarded' })}>{t.discarded}</button></div>}{complete.isError && <Alert tone="danger">{message(complete.error)}</Alert>}</li>)}</ul>}</div><aside className="urgency-rail" aria-labelledby="urgency-title"><div className="urgency-rail__heading"><p className="eyebrow">Ближайшее действие</p><h2 id="urgency-title">{t.urgency}</h2></div>{products.isPending ? <Skeleton /> : <ul>{urgent.map((item, index) => <li key={item.id}><span className="urgency-rank">0{index + 1}</span><div><strong>{item.name}</strong><p>{item.location || 'Не указано'} · <time dateTime={item.expiryDate}>{item.expiryDate}</time></p></div><StatusBadge status={item.status} /></li>)}</ul>}<div className="urgency-rail__note"><StatusBadge status="research_required" /><Alert>{t.ruleText}</Alert></div></aside></div>
}

const productSchema = z.object({ name: z.string().trim().min(1, 'Введите название'), dateType: z.enum(['use_by', 'best_before']), expiryDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Укажите дату'), location: z.string(), group: z.string() })
type FormData = z.infer<typeof productSchema>
const errorId = (field: keyof FormData) => `error-${field}`

function ProductForm({ title, defaults, onSave }: { title: string; defaults?: Partial<ProductInput>; onSave?: (input: ProductInput) => Promise<unknown> }) {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [serverError, setServerError] = useState<string>()
  const form = useForm<FormData>({ resolver: zodResolver(productSchema), defaultValues: { name: '', dateType: 'use_by', expiryDate: '', location: '', group: '', ...defaults } })
  const create = useMutation({ mutationFn: (input: ProductInput) => onSave ? onSave(input) : api.products.create(input), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: productKeys.list }); navigate('/products', { state: { notice: 'Продукт добавлен.' } }) }, onError: (error) => setServerError(message(error)) })
  const submit = (data: FormData) => { setServerError(undefined); create.mutate(data) }
  const field = (name: keyof FormData) => ({ 'aria-invalid': Boolean(form.formState.errors[name]), 'aria-describedby': form.formState.errors[name] ? errorId(name) : undefined })
  return <Page title={title}><form className="form-card" onSubmit={form.handleSubmit(submit)} noValidate><div className="form-grid"><label>Название<input {...form.register('name')} {...field('name')} />{form.formState.errors.name && <span id={errorId('name')} role="alert">{form.formState.errors.name.message}</span>}</label><label>Тип даты<select {...form.register('dateType')}><option value="use_by">Годен до</option><option value="best_before">Лучше употребить до</option></select></label><label>Дата<input type="date" {...form.register('expiryDate')} {...field('expiryDate')} />{form.formState.errors.expiryDate && <span id={errorId('expiryDate')} role="alert">{form.formState.errors.expiryDate.message}</span>}</label><label>Место хранения<input {...form.register('location')} /></label><label>Группа<input {...form.register('group')} /></label></div><Alert tone="info">«Годен до» — дата безопасности. «Лучше употребить до» — дата качества.</Alert>{serverError && <Alert tone="danger">{serverError}</Alert>}<div className="form-actions"><button type="submit" disabled={create.isPending}>{create.isPending ? 'Сохраняем…' : onSave ? 'Сохранить после проверки' : t.save}</button>{!onSave && <Link to="/products/new/photo">{t.photo}</Link>}</div></form></Page>
}

function PhotoUpload() { const navigate = useNavigate(); const recognize = useMutation({ mutationFn: api.drafts.recognize, onSuccess: (draft) => navigate(`/product-drafts/${draft.id}`) }); return <Page title={t.photo}><div className="card stack"><label>Фото упаковки<input type="file" accept="image/*" disabled={recognize.isPending} onChange={(event) => { const file = event.target.files?.[0]; if (file) recognize.mutate(file) }} /></label>{recognize.isPending && <Alert>Распознаём данные…</Alert>}{recognize.isError && <RequestError retry={() => recognize.reset()} />}<Link to="/products/new">{t.manual}</Link></div></Page> }

function DraftReview() { const { id = '' } = useParams(); const navigate = useNavigate(); const draft = useQuery({ queryKey: ['draft', id], queryFn: () => api.drafts.get(id), retry: false }); const reject = useMutation({ mutationFn: () => api.drafts.reject(id), onSuccess: () => navigate('/products/new') }); if (draft.isPending) return <Page title={t.draft}><Skeleton /></Page>; if (draft.isError) return <Page title="Не удалось открыть черновик"><RequestError retry={() => draft.refetch()} /></Page>; return <><ProductForm title={t.draft} defaults={draft.data.fields} onSave={(input) => api.drafts.approve(id, input)} /><div className="form-actions"><button className="button-secondary" disabled={reject.isPending} onClick={() => reject.mutate()}>{reject.isPending ? 'Отклоняем…' : 'Отклонить черновик'}</button>{reject.isError && <Alert tone="danger">{message(reject.error)}</Alert>}</div></> }

function ProductDetail() { const { id = '' } = useParams(); const queryClient = useQueryClient(); const product = useQuery({ queryKey: productKeys.detail(id), queryFn: () => api.products.get(id), retry: false }); const complete = useMutation({ mutationFn: (action: 'used' | 'discarded') => api.products.complete(id, action), onSuccess: () => { queryClient.invalidateQueries({ queryKey: productKeys.list }); product.refetch() } }); if (product.isPending) return <Page title="Продукт"><Skeleton /></Page>; if (product.isError) return <Page title="Не удалось открыть продукт"><RequestError retry={() => product.refetch()} /></Page>; const item = product.data; return <Page title={item.name}><section className="card stack"><StatusBadge status={item.status} /><p>{dateTypeLabel(item.dateType)}: <time dateTime={item.expiryDate}>{item.expiryDate}</time></p><p>{item.location || 'Место хранения не указано'}</p>{!['used', 'discarded'].includes(item.status) && <div className="form-actions"><button disabled={complete.isPending} onClick={() => complete.mutate('used')}>Использован</button><button className="button-secondary" disabled={complete.isPending} onClick={() => complete.mutate('discarded')}>Выброшен</button></div>}{complete.isError && <Alert tone="danger">{message(complete.error)}</Alert>}</section></Page> }

function Recipes() { const recipes = useQuery({ queryKey: ['recipes'], queryFn: api.recipes, retry: false }); return <Page title={t.recipes}>{recipes.isPending ? <Skeleton /> : recipes.isError ? <RequestError retry={() => recipes.refetch()} /> : recipes.data.length === 0 ? <EmptyState action={<Link to="/products">{t.products}</Link>}>{t.noRecipes}</EmptyState> : <ul className="product-list">{recipes.data.map((recipe) => <li className="card" key={recipe.title}><h2>{recipe.title}</h2><p>Рекомендация основана на доступных продуктах.</p></li>)}</ul>}</Page> }
function Settings() { return <Page title={t.settings}><section className="card stack"><Alert>{t.settingsBlocked}</Alert><p>{t.profileBlocked}</p><p className="muted">В этом окружении: {apiMode === 'fixture' ? 'тестовые данные разработки' : 'подключён API-сервер'}.</p></section></Page> }

function Credentials({ register }: { register?: boolean }) { const navigate = useNavigate(); const location = useLocation(); const queryClient = useQueryClient(); const [error, setError] = useState<string>(); const form = useForm<{ email: string; password: string }>({ defaultValues: { email: '', password: '' } }); const action = useMutation({ mutationFn: ({ email, password }: { email: string; password: string }) => register ? api.auth.register(email, password) : api.auth.login(email, password), onSuccess: async () => { if (register) { navigate('/login'); return } await queryClient.invalidateQueries({ queryKey: ['session'] }); navigate((location.state as { from?: string } | null)?.from ?? '/products') }, onError: (failure) => setError(message(failure)) }); return <PublicPage title={register ? t.register : t.login}>{register && <Alert tone="warning">{t.profileBlocked}</Alert>}<form className="form-card" onSubmit={form.handleSubmit((values) => { setError(undefined); action.mutate(values) })} noValidate><label>E-mail<input type="email" autoComplete="email" {...form.register('email', { required: 'Введите e-mail' })} /></label><label>Пароль<input type="password" autoComplete={register ? 'new-password' : 'current-password'} {...form.register('password', { required: 'Введите пароль', minLength: { value: 8, message: 'Минимум 8 символов' } })} /></label>{error && <Alert tone="danger">{error}</Alert>}<button disabled={action.isPending} type="submit">{action.isPending ? 'Отправляем…' : register ? t.register : t.login}</button><Link to={register ? '/login' : '/register'}>{register ? t.login : t.register}</Link></form></PublicPage> }

export function App() { return <Routes><Route path="/login" element={<Credentials />} /><Route path="/register" element={<Credentials register />} /><Route element={<ProtectedLayout />}><Route path="/products" element={<ProductList />} /><Route path="/products/new" element={<ProductForm title={t.add} />} /><Route path="/products/new/photo" element={<PhotoUpload />} /><Route path="/product-drafts/:id" element={<DraftReview />} /><Route path="/products/:id" element={<ProductDetail />} /><Route path="/recipes" element={<Recipes />} /><Route path="/settings" element={<Settings />} /></Route><Route path="*" element={<PublicPage title={t.notFound}><Link to="/products">{t.back}</Link></PublicPage>} /></Routes> }
